# Generated by Django 5.1.3 on 2024-12-01 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo_list',
            options={},
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='task',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='task_created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todo_list',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
